const coursedata = [
  {
    title: "Bachelor of Computer Applications(BCA)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bca",
  },
  {
    title: "Bachelors in Information Technology(BIT)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bit",
  },
  {
    title: "Bachelors in Information Management(BIM)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bim",
  },
  {
    title: "BSc Computer Science and Information Technology(B.Sc.CSIT)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bscs",
  },
  {
    title: "Bachelors in Computer Engineering(BE Computer) ",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/be",
  },
  {
    title: "Bachelors in Computer Engineering(BE Computer) ",
    university: "Pokhara University",
    years: "4 years",
    path: "/be1",
  },
  {
    title: "Bachelors in Computer Engineering(KUSOE) ",
    university: "Kathmandu University",
    years: "4 years",
    path: "/be2",
  },
  {
    title: "BSc Information Technology(BSc IT) ",
    university: "WestCliff University",
    years: "4 years",
    path: "/bsit",
  },
  {
    title: "BSc (Hons) Computing ",
    university: "Leeds Beckett University",
    years: "4 years",
    path: "/computing",
  },
  {
    title: "Bachelor of Computer Science and Information Technology(BCSIT)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/csit",
  },
  {
    title: "BSc (Hons) Computing ",
    university: "Leeds Beckett University",
    years: "4 years",
    path: "/computing",
  },
  {
    title: "Bachelors in Computer Science and Information Technology(BCSIT)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/csit",
  },
  {
    title: "Bachelor of Hotel Management(BHM)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bhm",
  },
  {
    title: "Bachelor of Business Management(BBM)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bbm",
  },
  {
    title: "Bachelor (Hons) of Business Administration(BBA)",
    university: "Lincoln University College",
    years: "4 years",
    path: "/bba",
  },
  {
    title: "Bachelor in Business Studies(BBS)",
    university: "Tribhuvan University",
    years: "4 years",
    path: "/bbs",
  },
  {
    title: "BSc (Hons) Computer Systems Engineering",
    university: "University of Sunderland",
    years: "3 years",
    path: "/be3",
  },
];
export default coursedata;
